### ISSUE TITLE
.rules not being read 

### ISSUE THREAD

**Issue by CarloCattano** [mzero/amidiminder#2]
```
sudo amidiminder -C
no rules file specified, so no rules added
```
I setted my simple rules at the /etc/amidiminder.rules , but I cant get it to read them 

Running on raspberry pi with PatchBox OS. Works like a charm otherwise , thanks for this marvellous tool !

**Comment by mzero** [comment]
If you want to check the rules before restarting the service, you need to tell the command which rules file to check:

```
amidiminder -C -f myrulesfile
```

If you are are editing `/etc/amidiminder.rules`, check it with:

```
amidiminder -C -f /etc/amidiminder.rules
```
