### ISSUE TITLE
Upgrading clobbers /etc/amidiminder.rules

### ISSUE THREAD

**Issue by p42ul** [mzero/amidiminder#3]
Steps to repro:

1. Create your own /etc/amidiminder.rules file.
2. Make a new version of amidiminder.
3. Use `sudo dpkg -i ...` to install the new version.

Your /etc/amidiminder.rules file is now the default. :(

**Comment by mzero** [comment]
No longer a concern. The 0.80 release persists state separately from /etc.

https://github.com/mzero/amidiminder/releases/tag/0.80
