### ISSUE TITLE
Check does not parse rules

### ISSUE THREAD

**Issue by paranoidi** [mzero/amidiminder#4]
Awesome project! I have been looking for a good mapping solution for hours and I was about to write my own in python. But this is just what I had in mind. Luckily I found this.

However, the check command does not seem to work (logically)

```
$ amidiminder -C
no rules file specified, so no rules added
```

After making changes I need to run

```
$ systemctl restart amidiminder
```

It'd be great if this was explicitly mentioned as a requirement to apply changes in the readme / example config. It would be good to mention what the `amidiminder` does when it's executed without any parameters.

**Comment by mzero** [comment]
You need to explicitly specify the rules file with the `-f` argument, like so:

    $ amidiminder -C -f /etc/amidiminder.rules

or whatever file you are checking.

**Comment by paranoidi** [comment]
@mzero Cool, I see. The documentation explicitly gives incorrect example and the stdout/err is adding to confusion. Maybe consider rephrasing it something like "Check (-C) requires rules file via -f argument". If falling back to default reading location in absence of -f is not something you're open to.

The help could use some love too
"-C check rules file then edit"

What does "then edit" mean? open file in a editor, apply changes? 

You can make this substantially better by minor UX improvements.

Working very nicely otherwise.
