### ISSUE TITLE
Cannot find any instructions on either creating or placing rules. 

### ISSUE THREAD

**Issue by pereshaped** [mzero/amidiminder#7]
A "man" manual command would be helpful.

Can run it fine in Pi and see the connections but nowhere does it describe how to save those rules into /etc

thanks

**Comment by mzero** [comment]
The 0.80 release now has full man pages.  You can read them once installed... or the repo has the .txt versions in the man directory. 

https://github.com/mzero/amidiminder/releases/tag/0.80
